coverage:
  status:
    project:
      default:
        target: 80%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
      front-end:
        target: 60%
       flags:
          - front-end
      back-end:
        target: 100%
        flags:
          - back-end

flags:
  front-end:
    paths: #note, accepts globs, not regexes
      - node
    carryforward: false
  back-end:
    paths: #note, accepts globs, not regexes
      - python
    carryforward: true

cli:
  plugins:
    pycoverage:
      report_type: "json"

comment:                  #this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: true       # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]]
