name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r python/requirements.txt

      - name: Run tests and collect coverage
        run: cd python && pytest --cov app ${{ env.CODECOV_ATS_TESTS }}

      - name: npm install -g codecov
        run: npm install -g codecov && npm install -g pnpm

      - name: npm install
        run: cd node && pnpm install

      - name: test node
        run: cd node && pnpm run unit

      - name: bundle install
        run: cd node && pnpm add @codecov/webpack-plugin 

      - name: build
        run: cd node && pnpm run build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          files: python/coverage.json
          flags: python
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          files: node/coverage/coverage-final.json
          flags: node
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
